README.md, feature/src/main/res/values/colors.xml, feature/src/main/res/values/themes.xml
=> [Feat/#5] color system setting

feature/src/main/java/com/teamkkumul/feature/home/HomeFragment.kt, feature/src/main/res/navigation/nav_graph.xml
=> #4 [chore] : fragment 백스택 관리 추가 / 더미파일

feature/src/main/res/drawable/shape_radius_8.xml, feature/src/main/res/drawable/shape_rect_200.xml, feature/src/main/res/drawable/shape_white0_radius_8.xml, feature/src/main/res/values/themes.xml
=> [Feat/#32] : share component

core/data/src/main/java/com/teamkkumul/core/data/mapper/AuthMapper.kt, core/data/src/main/java/com/teamkkumul/core/data/utils/getErrorMessage.kt, core/network/src/main/java/com/teamkkumul/core/network/dto/response/BaseResponse.kt
=> #52 [hotfix] : baseresponse 수정

core/data/src/main/java/com/teamkkumul/core/data/di/DataModule.kt, core/data/src/main/java/com/teamkkumul/core/data/mapper/MeetUpCreateMapper.kt, core/data/src/main/java/com/teamkkumul/core/data/repository/MeetUpCreateLocationRepository.kt, core/data/src/main/java/com/teamkkumul/core/data/repositoryimpl/MeetUpCreateLocationRepositoryImpl.kt, core/model/src/main/java/com/teamkkumul/model/MeetUpCreateLocationModel.kt, core/network/src/main/java/com/teamkkumul/core/network/api/MeetUpCreateService.kt, core/network/src/main/java/com/teamkkumul/core/network/di/ApiModule.kt, core/network/src/main/java/com/teamkkumul/core/network/dto/response/ResponseMeetUpCreateLocationDto.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateViewModel.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/location/MeetUpCreateLocationAdapter.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/location/MeetUpCreateLocationFragment.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/location/MeetUpCreateLocationViewHolder.kt, feature/src/main/res/layout/fragment_meet_up_create_location.xml
- closed #76 
https://github.com/user-attachments/assets/cbb988b2-b610-4fd9-aa15-6c2eaafb1d44
=> [Feat/#76] meet up create loaction 서버 통신

feature/src/main/java/com/teamkkumul/feature/meetupcreate/friend/MeetUpCreateFriendFragment.kt, feature/src/main/java/com/teamkkumul/feature/mypage/MyPageFragment.kt, feature/src/main/java/com/teamkkumul/feature/mypage/MyPageViewModel.kt, feature/src/main/res/drawable/ic_my_page_edit.xml, feature/src/main/res/drawable/ic_my_page_profile.xml, feature/src/main/res/drawable/sel_switch_thumb.xml, feature/src/main/res/drawable/sel_switch_track.xml, feature/src/main/res/drawable/shape_maincolor_fill_40_rect.xml, feature/src/main/res/layout/fragment_my_page.xml, feature/src/main/res/values/strings.xml
- closed #87
마지막에 사용자 이름이랑 level별로 mapping만 하면 될 것 같습니다
=> [Feat/#87] my page

feature/src/main/java/com/teamkkumul/feature/mygroup/MyGroupFragment.kt, feature/src/main/java/com/teamkkumul/feature/mygroup/MyGroupViewModel.kt, feature/src/main/java/com/teamkkumul/feature/signup/SetNameViewModel.kt, feature/src/main/java/com/teamkkumul/feature/splash/SplashViewModel.kt, feature/src/main/res/layout/fragment_my_page.xml
=> [Feat/#92] auto login nickname

core/network/src/main/java/com/teamkkumul/core/network/api/MyGroupService.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateViewModel.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/location/MeetUpCreateLocationFragment.kt
- closed #98 
-> 친구 추가 화면에 내가 안뜨게 됩니다.
=> [HOTFIX/#98] Query 파라미터 추가

core/data/src/main/java/com/teamkkumul/core/data/mapper/MeetUpCreateMapper.kt, core/data/src/main/java/com/teamkkumul/core/data/repository/MeetUpCreateLocationRepository.kt, core/data/src/main/java/com/teamkkumul/core/data/repositoryimpl/MeetUpCreateLocationRepositoryImpl.kt, core/model/src/main/java/com/teamkkumul/model/MeetUpCreateModel.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateCompleteFragment.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateFragment.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateViewModel.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/meetuplevel/MeetUpLevelFragment.kt, feature/src/main/res/layout/fragment_meet_up_create_complete.xml, feature/src/main/res/layout/item_ready_status.xml
=> #83 [hotfix] : 최종 오류 수정

feature/src/main/java/com/teamkkumul/feature/meetup/lateperson/LatePersonFragment.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateCompleteFragment.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateFragment.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/friend/MeetUpCreateFriendAdapter.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/friend/MeetUpCreateFriendFragment.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/meetuplevel/MeetUpLevelFragment.kt, feature/src/main/res/navigation/nav_graph.xml
=> #101 [hotfix] : 최종 오류 수정

.editorconfig
- closed #
제가 타 플젝을 코알라로 하게 되서 ktlint plugin버전 업데이트를 강제적으로 하게 됬는데
지금 이구아나용 ktlint버전에 맞추어 editConfig파일 만들었습니다!
호옥시 시간 된다면 이 pr pull받아서 돌려봐주시겠나요? 전 이제 이구아나가 사라져서ㅠㅠ
=> [hotfix] : ktlint 버전 업데이트 함에 따라 기존 속성 유지하도록 editconfig 설정

core/data/src/main/java/com/teamkkumul/core/data/mapper/HomeMapper.kt, core/model/src/main/java/com/teamkkumul/model/home/HomeTodayMeetingModel.kt, core/network/src/main/java/com/teamkkumul/core/network/dto/response/ResponseHomeUpComingMeetingDto.kt, core/network/src/main/java/com/teamkkumul/core/network/dto/response/ResponseTodayMeetingDto.kt, feature/src/main/java/com/teamkkumul/feature/home/viewholder/HomeMeetUpViewHolder.kt, feature/src/main/java/com/teamkkumul/feature/utils/time/formatTimeToPmAm.kt
- closed #134 
string의 확장함수로 만들어 놓았습니다!
=> [Feat/#134] time utils

core/data/src/main/java/com/teamkkumul/core/data/repository/MyGroupRepository.kt, core/data/src/main/java/com/teamkkumul/core/data/repositoryimpl/MyGroupRepositoryImpl.kt, core/network/src/main/java/com/teamkkumul/core/network/api/MyGroupService.kt, feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt, feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailViewModel.kt, feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogFragment.kt, feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogViewModel.kt, feature/src/main/res/layout/fragment_meet_up_detail.xml, feature/src/main/res/layout/fragment_my_group_detail.xml
- closed #
https://github.com/user-attachments/assets/c6d72210-149b-4e0f-8bbc-b71128d3a452
=> [Feat/#139] 모임 상세 페이지 서버통신 구현

feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusAdapter.kt, feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusFragment.kt, feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusViewModel.kt, feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/viewholder/ReadyStatusFriendItemDecoration.kt, feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/viewholder/ReadyStatusViewHolder.kt, feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogFragment.kt, feature/src/main/res/drawable/shape_rect_top_20.xml, feature/src/main/res/layout/fragment_dialog_delete.xml, feature/src/main/res/layout/fragment_ready_status.xml, feature/src/main/res/layout/item_ready_status.xml, gradle.properties
=> [UI/#145] our ready status UI

feature/src/main/java/com/teamkkumul/feature/meetupcreate/friend/MeetUpCreateFriendFragment.kt, feature/src/main/res/layout/fragment_meet_up_create.xml, feature/src/main/res/layout/fragment_meet_up_create_location.xml
=> [fix/#161] 코드 수정

app/src/main/AndroidManifest.xml, feature/src/main/AndroidManifest.xml, feature/src/main/res/layout/fragment_home.xml
=> #126 [hotfix] : 마진 에러 수정

feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateCompleteFragment.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateFragment.kt, feature/src/main/java/com/teamkkumul/feature/meetupcreate/meetuplevel/MeetUpLevelFragment.kt, feature/src/main/java/com/teamkkumul/feature/utils/time/TimeUtil.kt, feature/src/main/res/layout/fragment_meet_up_create_complete.xml, feature/src/main/res/layout/fragment_meet_up_level.xml
- closed #169 
https://github.com/user-attachments/assets/4015e001-7150-45e6-951c-c7e0d9a0743b
=> [Fix/#169] 1차 스프린트 QA 수정사항

app/proguard-rules.pro, app/src/main/AndroidManifest.xml, gradle/libs.versions.toml
- closed #167 
flip6에서 왜 안나오는지는..
릴리즈 모드에서 안나오는 건지 모르겠네요ㅠㅠ 제거에선 잘 나와서 이따 혜리 폰으로 테스트 해봐야할듯
=> [Hotfix/#167] firebase error

feature/src/main/java/com/teamkkumul/feature/home/HomeFragment.kt, feature/src/main/java/com/teamkkumul/feature/home/HomeViewModel.kt, feature/src/main/java/com/teamkkumul/feature/home/viewholder/HomeMeetUpViewHolder.kt, feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusViewModel.kt, feature/src/main/java/com/teamkkumul/feature/utils/extension/observeBtnState.kt, feature/src/main/java/com/teamkkumul/feature/utils/model/BtnState.kt, feature/src/main/java/com/teamkkumul/feature/utils/type/ReadyBtnTextType.kt, feature/src/main/res/values/strings.xml
=> [Hotfix/#172] home qa

feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readyinfoinput/ReadyInfoInputFragment.kt, feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readyinfoinput/ReadyInfoInputViewModel.kt, feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusFragment.kt, feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/ReadyStatusViewModel.kt, feature/src/main/java/com/teamkkumul/feature/meetup/readystatus/readystatus/model/TimeTextState.kt, feature/src/main/java/com/teamkkumul/feature/utils/time/TimeUtil.kt
=> [Hotfix/#171] ready status qa

feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt, feature/src/main/java/com/teamkkumul/feature/utils/itemdecorator/MeetUpFriendItemDecoration.kt, feature/src/main/res/layout/fragment_my_group_detail.xml, feature/src/main/res/layout/item_my_group_remain_meet_up.xml, feature/src/main/res/layout/view_toolbar.xml, feature/src/main/res/values/strings.xml
=> [Fix/#176] 2차 스프린트 QA

feature/src/main/res/layout/fragment_my_group_detail.xml
=> [fix/#176] 스프린트 3차 QA

feature/src/main/res/values/strings.xml
=> #199 [chore] : "을" 제거
